Mid meas
WattRex/Battery-Cycler-Controller pull request #35
Opened 2023-10-30 10:54 UTC by RobertoAldea

2023-10-30 13:47 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        except SysShdErrorC as err:
Change write to mergeExcluded

2023-10-30 13:52 UTC, mariuscrsn requested changes
Some minor changes required

2023-10-30 13:52 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        self.devices: MidDabsPwrMeterC = MidDabsPwrMeterC(devices)
Initialize also ExtraMeter if applicable

2023-10-30 13:52 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +
Read from shared measures

2023-10-30 13:52 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        except SysShdErrorC as err:
It can throw an exception?

2023-10-30 13:54 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        except SysShdErrorC as err:
If it can raise an error, print error stack trace

2023-10-30 13:54 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        self.devices: MidDabsPwrMeterC = MidDabsPwrMeterC(devices)
Change name following doc

2023-10-30 14:01 UTC, mariuscrsn requested changes
Some minor changes required

2023-10-30 14:01 UTC, mariuscrsn requested changes
Some minor changes required

2023-11-02 13:44 UTC, RobertoAldea commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +
Done

2023-11-02 13:44 UTC, RobertoAldea commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        self.devices: MidDabsPwrMeterC = MidDabsPwrMeterC(devices)
Done

2023-11-03 08:57 UTC, mariuscrsn requested changes

2023-11-03 08:57 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        # self.__meter_period: int = 10
Remove it

2023-11-03 08:57 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +        # Update the measurements and status of the extra devices.
Remove it

2023-11-03 08:57 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
> +            dev.update(self._ext_meas)
What happens if any device has an error?

2023-11-03 13:09 UTC, mariuscrsn approved these changes

2023-11-03 13:11 UTC, merged