App man
WattRex/Battery-Cycler-Controller pull request #73
Opened 2023-11-29 13:52 UTC by RobertoAldea

2023-11-30 14:17 UTC, mariuscrsn requested changes

2023-11-30 14:17 UTC, mariuscrsn commented on code/cycler/src/wattrex_battery_cycler/app/app_man/app_man_core.py
> +        for dev in pwr_devices:
move it dabs

2023-12-01 12:32 UTC, RobertoAldea commented on code/cycler/src/wattrex_battery_cycler/app/app_man/app_man_core.py
> +        for dev in pwr_devices:
Done

2023-12-01 12:33 UTC, mariuscrsn approved these changes

2023-12-01 12:37 UTC, merged